Repository stolostron/cluster-curator-controller, pull requests merged in 2024-09, with the labels that each got.

#265 ACM-13470: add ansiblejob dependency api code, remove old dependencies
  go.mod
  go.sum
  pkg/api/v1alpha1/ansiblejob_types.go
  pkg/api/v1alpha1/groupversion_info.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/jobs/ansible/job_test.go
  pkg/jobs/utils/helpers.go
Labels: dco-signoff: yes

#266 ACM-13470: upgrade hive in clc repos
  Dockerfile.prow
  Dockerfile.rhtap
  go.mod
  go.sum
  pkg/jobs/secrets/secrets_test.go
Labels: lgtm, approved, dco-signoff: yes

#262 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/cluster-curator-controller-mce-25-pull-request.yaml
  .tekton/cluster-curator-controller-mce-25-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#263 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/cluster-curator-controller-mce-26-pull-request.yaml
  .tekton/cluster-curator-controller-mce-26-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#274 ACM-14464: update hive api dependency
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes
